ISO_BOOT_MODE='live'
TARGET_ARCH='aarch64'
WM_DE='none'
DISPLAY_MANAGER='none'
X_STACK='xorg'
INIT='openrc'
KERNEL_CHOICE='linux-aarch64'
NETWORK_STACK='dhcpcd+iwd'
AUDIO_STACK='none'
ISO_EXTRA_PACKAGES=''
ISO_OUTPUT_DIR="${HOME}/ArtixForge-ISO"
ALLOW_OFFLINE='no'